<a href="https://colab.research.google.com/github/cras-lab/ML-examples/blob/main/KNN_%EB%B6%93%EA%BD%83%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Knn 알고리즘을 이용하여, 붓꽃을 분류해 본다.<BR>
우선 필요한 모듈을 임포트 한다.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

붓꽃 데이터를 불러온다.

In [2]:
# 데이터 불러오기
iris = load_iris()
X = iris.data
y = iris.target

프린트 하여, 내용을 살펴본다.

In [3]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

데이터를 8:2로 분할한다.

In [4]:
# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

KNN 분류기를 생성한다.

In [5]:
# KNN 분류기 생성
knn_classifier = KNeighborsClassifier(n_neighbors=3)  # \ n_neighbors의 디폴트 값은 5

모델을 학습시킨다

In [6]:
# 모델 학습
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

테스트 데이터를 상대로 예측을 수행해 본다.

In [7]:
# 테스트 데이터 예측
y_pred = knn_classifier.predict(X_test)

정확도를 평가해 본다.

In [8]:
# 정확도 평가
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy:, {accuracy:.3f}')

Accuracy:, 0.967


직접 몇 가지 측정 값을 넣어서, 예측을 수행해 본다.

In [15]:
test_X = [
    [6.0,3.1, 5.0, 2.2],
    [7.0,2.1, 3.1, 1.1],
    [6.1,5.1, 6.5, 6.1]
]

test_Y = knn_classifier.predict(test_X)

print(test_Y)

[2 1 2]
